
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const AnonymousLogin = lazy(() => import("./pages/AnonymousLogin.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const BookDetails = lazy(() => import("./pages/BookDetails.tsx"));
const CreateBook = lazy(() => import("./pages/CreateBook.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/anonymous-login", element: <UserGuard><AnonymousLogin /></UserGuard>},
	{ path: "/anonymouslogin", element: <UserGuard><AnonymousLogin /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/book-details", element: <UserGuard><BookDetails /></UserGuard>},
	{ path: "/bookdetails", element: <UserGuard><BookDetails /></UserGuard>},
	{ path: "/create-book", element: <UserGuard><CreateBook /></UserGuard>},
	{ path: "/createbook", element: <UserGuard><CreateBook /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/profile", element: <UserGuard><Profile /></UserGuard>},
	{ path: "/signup", element: <UserGuard><Signup /></UserGuard>},

];
